version: '3'
services:
  dev-proxy:
    image: ghcr.io/linuxserver/nginx
    volumes:
      - ./docker:/config
      - ./:/app
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/New_York
